import { UserRole } from '../types';

export const PERMISSIONS = {
  // Students
  STUDENTS_READ: 'students.read',
  STUDENTS_CREATE: 'students.create',
  STUDENTS_UPDATE: 'students.update',
  STUDENTS_DELETE: 'students.delete',

  // Faculty
  FACULTY_READ: 'faculty.read',
  FACULTY_MANAGE: 'faculty.manage',

  // Departments & Courses
  DEPARTMENTS_MANAGE: 'departments.manage',
  COURSES_MANAGE: 'courses.manage',

  // Attendance
  ATTENDANCE_READ: 'attendance.read',
  ATTENDANCE_RECORD: 'attendance.record',
  ATTENDANCE_CORRECT: 'attendance.correct',
  ATTENDANCE_APPROVE: 'attendance.approve',

  // Timetable
  TIMETABLE_READ: 'timetable.read',
  TIMETABLE_EDIT: 'timetable.edit',

  // Assignments
  ASSIGNMENTS_READ: 'assignments.read',
  ASSIGNMENTS_CREATE: 'assignments.create',
  ASSIGNMENTS_GRADE: 'assignments.grade',
  ASSIGNMENTS_SUBMIT: 'assignments.submit',

  // Exams & Marks
  MARKS_READ: 'marks.read',
  MARKS_ENTER: 'marks.enter',
  MARKS_VERIFY: 'marks.verify',
  MARKS_LOCK_PUBLISH: 'marks.lock_publish',

  // Fees & Ledgers
  FEES_READ: 'fees.read',
  FEES_COLLECT: 'fees.collect',
  FEES_REFUND: 'fees.refund',

  // Approvals & Audit
  APPROVALS_MANAGE: 'approvals.manage',
  AUDIT_READ: 'audit.read',
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

// Centralized Role-Permission mapping
const ROLE_PERMISSIONS_MAP: Record<UserRole, PermissionCode[]> = {
  SUPER_ADMIN: Object.values(PERMISSIONS),
  COLLEGE_ADMIN: [
    PERMISSIONS.STUDENTS_READ,
    PERMISSIONS.STUDENTS_CREATE,
    PERMISSIONS.STUDENTS_UPDATE,
    PERMISSIONS.FACULTY_READ,
    PERMISSIONS.FACULTY_MANAGE,
    PERMISSIONS.DEPARTMENTS_MANAGE,
    PERMISSIONS.COURSES_MANAGE,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.ATTENDANCE_APPROVE,
    PERMISSIONS.TIMETABLE_READ,
    PERMISSIONS.TIMETABLE_EDIT,
    PERMISSIONS.ASSIGNMENTS_READ,
    PERMISSIONS.MARKS_READ,
    PERMISSIONS.MARKS_VERIFY,
    PERMISSIONS.MARKS_LOCK_PUBLISH,
    PERMISSIONS.FEES_READ,
    PERMISSIONS.FEES_COLLECT,
    PERMISSIONS.FEES_REFUND,
    PERMISSIONS.APPROVALS_MANAGE,
    PERMISSIONS.AUDIT_READ,
  ],
  PRINCIPAL: [
    PERMISSIONS.STUDENTS_READ,
    PERMISSIONS.FACULTY_READ,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.ATTENDANCE_APPROVE,
    PERMISSIONS.TIMETABLE_READ,
    PERMISSIONS.ASSIGNMENTS_READ,
    PERMISSIONS.MARKS_READ,
    PERMISSIONS.MARKS_VERIFY,
    PERMISSIONS.FEES_READ,
    PERMISSIONS.APPROVALS_MANAGE,
    PERMISSIONS.AUDIT_READ,
  ],
  HOD: [
    PERMISSIONS.STUDENTS_READ,
    PERMISSIONS.FACULTY_READ,
    PERMISSIONS.COURSES_MANAGE,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.ATTENDANCE_APPROVE,
    PERMISSIONS.TIMETABLE_READ,
    PERMISSIONS.TIMETABLE_EDIT,
    PERMISSIONS.ASSIGNMENTS_READ,
    PERMISSIONS.MARKS_READ,
    PERMISSIONS.MARKS_VERIFY,
    PERMISSIONS.APPROVALS_MANAGE,
  ],
  FACULTY: [
    PERMISSIONS.STUDENTS_READ,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.ATTENDANCE_RECORD,
    PERMISSIONS.ATTENDANCE_CORRECT,
    PERMISSIONS.TIMETABLE_READ,
    PERMISSIONS.ASSIGNMENTS_READ,
    PERMISSIONS.ASSIGNMENTS_CREATE,
    PERMISSIONS.ASSIGNMENTS_GRADE,
    PERMISSIONS.MARKS_READ,
    PERMISSIONS.MARKS_ENTER,
  ],
  STUDENT: [
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.TIMETABLE_READ,
    PERMISSIONS.ASSIGNMENTS_READ,
    PERMISSIONS.ASSIGNMENTS_SUBMIT,
    PERMISSIONS.MARKS_READ,
    PERMISSIONS.FEES_READ,
  ],
  PARENT: [
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.MARKS_READ,
    PERMISSIONS.FEES_READ,
  ],
  ACCOUNTANT: [
    PERMISSIONS.STUDENTS_READ,
    PERMISSIONS.FEES_READ,
    PERMISSIONS.FEES_COLLECT,
    PERMISSIONS.FEES_REFUND,
    PERMISSIONS.APPROVALS_MANAGE,
  ],
  EXAM_CELL: [
    PERMISSIONS.STUDENTS_READ,
    PERMISSIONS.MARKS_READ,
    PERMISSIONS.MARKS_VERIFY,
    PERMISSIONS.MARKS_LOCK_PUBLISH,
  ],
  LIBRARIAN: [PERMISSIONS.STUDENTS_READ],
  PLACEMENT_OFFICER: [PERMISSIONS.STUDENTS_READ],
  HOSTEL_ADMIN: [PERMISSIONS.STUDENTS_READ],
  TRANSPORT_ADMIN: [PERMISSIONS.STUDENTS_READ],
  AUDITOR: [
    PERMISSIONS.STUDENTS_READ,
    PERMISSIONS.FACULTY_READ,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.MARKS_READ,
    PERMISSIONS.FEES_READ,
    PERMISSIONS.AUDIT_READ,
  ],
};

export function hasPermission(role: UserRole, permission: PermissionCode): boolean {
  const allowed = ROLE_PERMISSIONS_MAP[role] || [];
  return allowed.includes(permission);
}

export function can(
  user: { role?: UserRole; permissions?: string[] } | null | undefined,
  permission: PermissionCode | string
): boolean {
  if (!user) return false;
  if (user.role === 'SUPER_ADMIN') return true;
  if (Array.isArray(user.permissions) && user.permissions.includes(permission)) return true;
  if (user.role) return hasPermission(user.role, permission as PermissionCode);
  return false;
}
